env:
  browser: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  curly: [2, multi-or-nest, consistent]
  no-return-assign: 0
  symbol-description: 0
